<?php
                                        	


  $ConstantsArray = array('dbServerUrl' => '/home/envirote/public_html/app/',

  'applicationURL'=>'http://www.envirotechlive.com/app/',
  'rootURL'=>'http://www.envirotechlive.com/',
  'logger' => 'myDBLogger'
  );

  $PERMISSION_MANAGER = "Manager";

  $PERMISSION_USER = "User";

  

  $Log4PHP_MyDBLogger = "myDBLogger";

  $Log4PHP_MyMailerLogger = "myMailerLogger";

  $Log4PHP_MyFileLogger = "myFileLogger";



?>