<?php
                                        	


  $ConstantsArray = array('dbServerUrl' => 'D:/projects/eliveProject/eliveui/',

  'applicationURL'=>'http://localhost:8080/eliveui/',
  'rootURL'=>'http://localhost:8080/',
  'logger' => 'myDBLogger'
  );

  $PERMISSION_MANAGER = "Manager";

  $PERMISSION_USER = "User";

  

  $Log4PHP_MyDBLogger = "myDBLogger";

  $Log4PHP_MyMailerLogger = "myMailerLogger";

  $Log4PHP_MyFileLogger = "myFileLogger";



?>